// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type IpEntrypointFarInfo struct {
	Action                uint8
	OuterHeaderCreation   uint8
	_                     [2]byte
	Teid                  uint32
	Remoteip              uint32
	Localip               uint32
	IfIndex               uint32
	TransportLevelMarking uint16
	_                     [2]byte
}

type IpEntrypointIn6Addr struct{ In6U struct{ U6Addr8 [16]uint8 } }

type IpEntrypointPdrInfo struct {
	FarId              uint32
	QerId              uint32
	OuterHeaderRemoval uint8
	SdfMode            uint8
	_                  [6]byte
	SdfRules           struct {
		SdfFilter struct {
			Protocol uint8
			_        [15]byte
			SrcAddr  struct {
				Type uint8
				_    [15]byte
				Ip   [16]byte /* uint128 */
				Mask [16]byte /* uint128 */
			}
			SrcPort struct {
				LowerBound uint16
				UpperBound uint16
			}
			_       [12]byte
			DstAddr struct {
				Type uint8
				_    [15]byte
				Ip   [16]byte /* uint128 */
				Mask [16]byte /* uint128 */
			}
			DstPort struct {
				LowerBound uint16
				UpperBound uint16
			}
			_ [12]byte
		}
		OuterHeaderRemoval uint8
		_                  [3]byte
		FarId              uint32
		QerId              uint32
		_                  [4]byte
	}
}

type IpEntrypointQerInfo struct {
	UlGateStatus     uint8
	DlGateStatus     uint8
	Qfi              uint8
	_                [1]byte
	UlMaximumBitrate uint32
	DlMaximumBitrate uint32
	_                [4]byte
	UlStart          uint64
	DlStart          uint64
}

type IpEntrypointRouteStat struct {
	FibLookupIp4Cache     uint64
	FibLookupIp4Ok        uint64
	FibLookupIp4ErrorDrop uint64
	FibLookupIp4ErrorPass uint64
	FibLookupIp6Cache     uint64
	FibLookupIp6Ok        uint64
	FibLookupIp6ErrorDrop uint64
	FibLookupIp6ErrorPass uint64
}

type IpEntrypointUpfStatistic struct {
	UpfCounters struct {
		RxArp      uint64
		RxIcmp     uint64
		RxIcmp6    uint64
		RxIp4      uint64
		RxIp6      uint64
		RxTcp      uint64
		RxUdp      uint64
		RxOther    uint64
		RxGtpEcho  uint64
		RxGtpPdu   uint64
		RxGtpOther uint64
		RxGtpUnexp uint64
	}
	UpfN3N6Counter struct {
		RxN3 uint64
		TxN3 uint64
		RxN6 uint64
		TxN6 uint64
	}
	XdpActions [8]uint64
}

// LoadIpEntrypoint returns the embedded CollectionSpec for IpEntrypoint.
func LoadIpEntrypoint() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IpEntrypointBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load IpEntrypoint: %w", err)
	}

	return spec, err
}

// LoadIpEntrypointObjects loads IpEntrypoint and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*IpEntrypointObjects
//	*IpEntrypointPrograms
//	*IpEntrypointMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadIpEntrypointObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadIpEntrypoint()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// IpEntrypointSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpEntrypointSpecs struct {
	IpEntrypointProgramSpecs
	IpEntrypointMapSpecs
}

// IpEntrypointSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpEntrypointProgramSpecs struct {
	UpfIpEntrypointFunc *ebpf.ProgramSpec `ebpf:"upf_ip_entrypoint_func"`
}

// IpEntrypointMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpEntrypointMapSpecs struct {
	FarMap            *ebpf.MapSpec `ebpf:"far_map"`
	PdrMapDownlinkIp4 *ebpf.MapSpec `ebpf:"pdr_map_downlink_ip4"`
	PdrMapDownlinkIp6 *ebpf.MapSpec `ebpf:"pdr_map_downlink_ip6"`
	PdrMapUplinkIp4   *ebpf.MapSpec `ebpf:"pdr_map_uplink_ip4"`
	QerMap            *ebpf.MapSpec `ebpf:"qer_map"`
	UpfExtStat        *ebpf.MapSpec `ebpf:"upf_ext_stat"`
	UpfPipeline       *ebpf.MapSpec `ebpf:"upf_pipeline"`
	UpfRouteStat      *ebpf.MapSpec `ebpf:"upf_route_stat"`
}

// IpEntrypointObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadIpEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpEntrypointObjects struct {
	IpEntrypointPrograms
	IpEntrypointMaps
}

func (o *IpEntrypointObjects) Close() error {
	return _IpEntrypointClose(
		&o.IpEntrypointPrograms,
		&o.IpEntrypointMaps,
	)
}

// IpEntrypointMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadIpEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpEntrypointMaps struct {
	FarMap            *ebpf.Map `ebpf:"far_map"`
	PdrMapDownlinkIp4 *ebpf.Map `ebpf:"pdr_map_downlink_ip4"`
	PdrMapDownlinkIp6 *ebpf.Map `ebpf:"pdr_map_downlink_ip6"`
	PdrMapUplinkIp4   *ebpf.Map `ebpf:"pdr_map_uplink_ip4"`
	QerMap            *ebpf.Map `ebpf:"qer_map"`
	UpfExtStat        *ebpf.Map `ebpf:"upf_ext_stat"`
	UpfPipeline       *ebpf.Map `ebpf:"upf_pipeline"`
	UpfRouteStat      *ebpf.Map `ebpf:"upf_route_stat"`
}

func (m *IpEntrypointMaps) Close() error {
	return _IpEntrypointClose(
		m.FarMap,
		m.PdrMapDownlinkIp4,
		m.PdrMapDownlinkIp6,
		m.PdrMapUplinkIp4,
		m.QerMap,
		m.UpfExtStat,
		m.UpfPipeline,
		m.UpfRouteStat,
	)
}

// IpEntrypointPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadIpEntrypointObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpEntrypointPrograms struct {
	UpfIpEntrypointFunc *ebpf.Program `ebpf:"upf_ip_entrypoint_func"`
}

func (p *IpEntrypointPrograms) Close() error {
	return _IpEntrypointClose(
		p.UpfIpEntrypointFunc,
	)
}

func _IpEntrypointClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ipentrypoint_bpf.o
var _IpEntrypointBytes []byte
