/*
 * Nnef_PFDmanagement Sevice API
 *
 * Packet Flow Description Management Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PfdChangeReport struct {
	PfdError      *ProblemDetails `json:"pfdError" yaml:"pfdError" bson:"pfdError"`
	ApplicationId []string        `json:"applicationId" yaml:"applicationId" bson:"applicationId"`
}
