/*
 * Nnef_PFDmanagement Sevice API
 *
 * Packet Flow Description Management Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PfdChangeNotification struct {
	ApplicationId string       `json:"applicationId" yaml:"applicationId" bson:"applicationId"`
	RemovalFlag   bool         `json:"removalFlag,omitempty" yaml:"removalFlag" bson:"removalFlag"`
	PartialFlag   bool         `json:"partialFlag,omitempty" yaml:"partialFlag" bson:"partialFlag"`
	Pfds          []PfdContent `json:"pfds,omitempty" yaml:"pfds" bson:"pfds"`
}
