/**
 * SPDX-License-Identifier: Apache-2.0
 * © Copyright 2023 Hewlett Packard Enterprise Development LP
 * © Copyright 2024 Valentin D'Emmanuele
 */
package pdu_session_management

import (
	"my5G-RANTester/internal/control_test_engine/gnb/context"
	"net/netip"

	ngap "github.com/free5gc/ngap/message"

	ngapType "github.com/free5gc/ngap/ie"
	ngapConvert "my5G-RANTester/lib/ngap"
)

type PDUSessionResourceSetupResponseBuilder struct {
	pdu *ngap.PDUSessionResourceSetupResponse
}

func PDUSessionResourceSetupResponse(pduSessions []*context.GnbPDUSession, ue *context.GNBUe, gnb *context.GNBContext) ([]byte, error) {
	return NewPDUSessionResourceSetupResponseBuilder().
		SetAmfUeNgapId(ue.GetAmfUeId()).SetRanUeNgapId(ue.GetRanUeId()).
		SetPDUSessionResourceSetupListSURes(gnb, pduSessions).
		Build()
}

func NewPDUSessionResourceSetupResponseBuilder() *PDUSessionResourceSetupResponseBuilder {
	pdu := &ngap.PDUSessionResourceSetupResponse{}
	return &PDUSessionResourceSetupResponseBuilder{pdu}
}

func (builder *PDUSessionResourceSetupResponseBuilder) SetAmfUeNgapId(amfUeNgapID int64) *PDUSessionResourceSetupResponseBuilder {
	builder.pdu.AMFUENGAPID = &ngapType.AMFUENGAPID{Value: amfUeNgapID}
	return builder
}

func (builder *PDUSessionResourceSetupResponseBuilder) SetRanUeNgapId(ranUeNgapID int64) *PDUSessionResourceSetupResponseBuilder {
	builder.pdu.RANUENGAPID = &ngapType.RANUENGAPID{Value: ranUeNgapID}
	return builder
}

func (builder *PDUSessionResourceSetupResponseBuilder) SetPDUSessionResourceSetupListSURes(gnb *context.GNBContext, pduSessions []*context.GnbPDUSession) *PDUSessionResourceSetupResponseBuilder {
	// PDU Session Resource Setup Response List
	ie := ngapType.PDUSessionResourceSetupResponseIEs{}

	ie.PDUSessionResourceSetupListSURes = new(ngapType.PDUSessionResourceSetupListSURes)

	pDUSessionResourceSetupListSURes := ie.PDUSessionResourceSetupListSURes

	for _, pduSession := range pduSessions {
		if pduSession == nil {
			continue
		}

		// PDU Session Resource Setup Response Item in PDU Session Resource Setup Response List
		pDUSessionResourceSetupItemSURes := ngapType.PDUSessionResourceSetupItemSURes{}

		// PDU Session ID : This is an unique identifier generated by UE. Can’t be same as any existing PDU session.
		pDUSessionResourceSetupItemSURes.PDUSessionID = &ngapType.PDUSessionID{Value: pduSession.GetPduSessionId()}

		pDUSessionResourceSetupItemSURes.PDUSessionResourceSetupResponseTransfer = ngapConvert.Octets(GetPDUSessionResourceSetupResponseTransfer(gnb.GetN3GnbIp(), pduSession.GetTeidDownlink(), pduSession.GetQosId()))

		pDUSessionResourceSetupListSURes.List = append(pDUSessionResourceSetupListSURes.List, pDUSessionResourceSetupItemSURes)
	}
	builder.pdu.PDUSessionResourceSetupListSURes = ie.PDUSessionResourceSetupListSURes

	return builder
}

func (builder *PDUSessionResourceSetupResponseBuilder) SetPDUSessionResourceFailedToSetupListSURes(gnb *context.GNBContext, pduSessions []*context.GnbPDUSession) *PDUSessionResourceSetupResponseBuilder {

	// PDU Sessuin Resource Failed to Setup List
	// ie = ngapType.PDUSessionResourceSetupResponseIEs{}
	// ie.Id.Value = ngapType.ProtocolIEIDPDUSessionResourceFailedToSetupListSURes
	// ie.Criticality.Value = ngapType.CriticalityPresentIgnore
	// ie.Present = ngapType.PDUSessionResourceSetupResponseIEsPresentPDUSessionResourceFailedToSetupListSURes
	// ie.PDUSessionResourceFailedToSetupListSURes = new(ngapType.PDUSessionResourceFailedToSetupListSURes)

	// pDUSessionResourceFailedToSetupListSURes := ie.PDUSessionResourceFailedToSetupListSURes

	// // PDU Session Resource Failed to Setup Item in PDU Sessuin Resource Failed to Setup List
	// pDUSessionResourceFailedToSetupItemSURes := ngapType.PDUSessionResourceFailedToSetupItemSURes{}
	// pDUSessionResourceFailedToSetupItemSURes.PDUSessionID = &ngapType.PDUSessionID{Value: 10}
	// pDUSessionResourceFailedToSetupItemSURes.PDUSessionResourceSetupUnsuccessfulTransfer = GetPDUSessionResourceSetupUnsucessfulTransfer()

	// pDUSessionResourceFailedToSetupListSURes.List = append(pDUSessionResourceFailedToSetupListSURes.List, pDUSessionResourceFailedToSetupItemSURes)

	// pdu.PDUSessionResourceFailedToSetupListSURes = ie.PDUSessionResourceFailedToSetupListSURes
	// Criticality Diagnostics (optional)
	return builder
}

func (builder *PDUSessionResourceSetupResponseBuilder) Build() ([]byte, error) {
	return builder.pdu.MarshalBinary()
}

func GetPDUSessionResourceSetupResponseTransfer(ipv4 netip.Addr, teid uint32, qosId int64) []byte {
	data := buildPDUSessionResourceSetupResponseTransfer(ipv4, teid, qosId)
	encodeData, _ := ngapConvert.Marshal(&data)
	return encodeData
}

func buildPDUSessionResourceSetupResponseTransfer(ipv4 netip.Addr, teid uint32, qosId int64) (data ngapType.PDUSessionResourceSetupResponseTransfer) {
	data.DLQosFlowPerTNLInformation = &ngapType.QosFlowPerTNLInformation{
		UPTransportLayerInformation: ngapConvert.UPTransport(ipv4, teid),
		AssociatedQosFlowList:       &ngapType.AssociatedQosFlowList{List: []ngapType.AssociatedQosFlowItem{{QosFlowIdentifier: &ngapType.QosFlowIdentifier{Value: qosId}}}},
	}
	return data
}
